export const ASYNC_STORAGE_KEYS = {
  TOTAL_RECORDS_DISPLAYED: 'TOTAL_RECORDS_DISPLAYED',
  TOTAL_RECORDS_AVAILABLE: 'TOTAL_RECORDS_AVAILABLE',
  TO_DATE: 'TO_DATE',
  DAY_BEFORE_COUNT: 'DAY_BEFORE_COUNT',
  IS_FULL_DATA_DISPLAYED: 'IS_FULL_DATA_DISPLAYED',
};
